-- AlterTable
ALTER TABLE "SavedVerbs" ALTER COLUMN "spanish" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "french" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "german" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "italian" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "portuguese" SET DEFAULT ARRAY[]::TEXT[];
